(defun card-game-for-two (n a)
  (let ((alice 0)
        (bob 0))
    (setf a (sort a #'>))
    (dotimes (i n)
      (if (zerop (rem i 2))
          (setf alice (+ alice (aref a i)))
          (setf bob (+ bob (aref a i)))))
    (- alice bob)))

(defun create-data ()
  (let* ((n (read))
         (a (make-array `(,n))))
    (dotimes (i n)
      (setf (aref a i) (read)))
    (values n a)))

(multiple-value-bind (n a) (create-data)
  (format t "~A~%" (card-game-for-two n a)))
