(defun kagami-mochi (n a)
  (let ((res 0)
        (num (make-array '(110) :initial-element 0)))
    (dotimes (i n)
      (incf (aref num (aref a i))))
    (dotimes (i 101)
      (if (> (aref num i) 0)
          (incf res)))
    res))

(defun create-data ()
  (let* ((n (read))
         (a (make-array `(,n))))
    (dotimes (i n)
      (setf (aref a i) (read)))
    (values n a)))

(multiple-value-bind (n a) (create-data)
  (format t "~A~%" (kagami-mochi n a)))
